### ISSUE TITLE
CTM issue in ATM9

### ISSUE THREAD

**Issue by tomascryogen** [matthewperiut/factory_blocks#9]
Hello,

Thank you for reviving these blocks.

I added your mod to ATM9 v9-0.3.2
The following mods are installed:
Chisel-forge-1.20.1-1.8.0
Rechiseled-1.1.6-forge-mc1.20
Chipped-forge-1.20.1-3.0.6
Athena-forge-1.20.1-3.1.2

Is there any way to make the connected textures on the fans work with these?

Regards,
Tom
![Screenshot](https://github.com/user-attachments/assets/dad30257-fa18-436e-987b-8bd79584d42a)

**Comment by matthewperiut** [comment]
I apologize I don't understand the question, what's wrong with the fans?

**Comment by tomascryogen** [comment]
I would like to have one large fan if that is possible like a 2x2 or a 3x3. Like the one on the right side here:
![image](https://github.com/user-attachments/assets/39a38bed-02d2-4ec0-a132-ffbdbefeafe6)

**Comment by matthewperiut** [comment]
I understand now, I implemented the larger 2x2 fan and didn't finish the feature, I'll go ahead and looking into making the 2x2 and 3x3 fans again because i have a good idea on how to do it.

You can currently access the 2x2 fan in creative if you need it for a creative build but it will be removed when i add the proper 2x2 and 3x3.

**Comment by tomascryogen** [comment]
Awesome! Thanks a lot for the work!
